### ISSUE TITLE
Difference?

### ISSUE THREAD

**Issue by Sattishh** [NezuChan/better-erela.js-apple#5]
Hey, I was wondering what the difference is in this package compared to the regular erela.js-apple. Can you tell me the specific things that are changed or made better?

**Comment by KagChi** [comment]
> Hey, I was wondering what the difference is in this package compared to the regular erela.js-apple. Can you tell me the specific things that are changed or made better?

in regular erela.js-apple duration are randomized and does not support full coverage of apple music routes. they does not support artist top tracks.

**Comment by KagChi** [comment]
![image](https://user-images.githubusercontent.com/59391215/144389198-a88f997b-7a86-4c64-bb5f-1559b530470a.png)

some of their code i dig into their package
